# Generated by Django 3.2.20 on 2023-10-21 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0033_auto_20231020_1722"),
        ("people", "0033_update_skill_and_action_tags"),
    ]

    operations = []
