# Generated by Django 3.2.20 on 2023-10-21 02:14

import agir.lib.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0034_merge_20231020_2009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("CAM", "Newsletter Claudializate"),
                        ("ACT", "Newsletter Red Migrante"),
                        ("LIA", "Correspondant·es d'immeuble ou de rue"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
