# Generated by Django 3.2.20 on 2023-11-08 19:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingstationofficer',
            name='birth_country',
            field=django_countries.fields.CountryField(default='MX', max_length=2, verbose_name='pays de naissance'),
        ),
    ]
