# Generated by Django 3.2.20 on 2023-10-19 22:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MexicanState",
            options={"ordering": ("code",), "verbose_name": "Mexican State"},
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=2, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        editable=False, max_length=70, verbose_name="Name"
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326, verbose_name="Geometry"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MexicanMunicipio",
            options={"ordering": ("code",), "verbose_name": "Mexican Municipio"},
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=5, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("M", "Municipio"), ("D", "Demarcacíon territorial")],
                        editable=False,
                        max_length=1,
                        verbose_name="Type",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326, verbose_name="Geometry"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="geodata.mexicanstate",
                        verbose_name="State",
                    ),
                ),
            ],
        ),
    ]
