# Generated by Django 3.2.20 on 2023-10-20 17:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations

install_unaccent = "CREATE EXTENSION IF NOT EXISTS unaccent;"

create_search_config = """
CREATE TEXT SEARCH CONFIGURATION places ( COPY = simple );
ALTER TEXT SEARCH CONFIGURATION places
  ALTER MAPPING FOR hword, hword_part, word
  WITH unaccent, simple;
"""

delete_search_config = "DROP TEXT SEARCH CONFIGURATION places;"


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0002_us_data"),
    ]

    operations = [
        migrations.RunSQL(
            sql=install_unaccent,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=create_search_config,
            reverse_sql=delete_search_config,
        ),
        migrations.AddField(
            model_name="mexicanmunicipio",
            name="search",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="uscounty",
            name="search",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="mexicanmunicipio",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search"], name="geodata_mex_search_219af2_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="uscounty",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search"], name="geodata_usc_search_ad4c2e_gin"
            ),
        ),
    ]
