# Generated by Django 3.2.20 on 2023-10-20 20:06


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0053_remove_unused_options_for_newsletters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segment",
            name="departements",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="donation_after",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="donation_not_after",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="donation_total_max",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="donation_total_min",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="donation_total_range",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="elu",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="elu_consulaire",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="elu_departemental",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="elu_depute",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="elu_depute_europeen",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="elu_municipal",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="elu_regional",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="elu_status",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="is_2022",
        ),
        migrations.RemoveField(
            model_name="segment",
            name="is_insoumise",
        ),
    ]
