# Generated by Django 3.2.20 on 2023-10-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0003_search"),
        ("mailing", "0054_auto_20231020_1406"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segment",
            name="subscription",
        ),
        migrations.AddField(
            model_name="segment",
            name="municipio_of_origin",
            field=models.ManyToManyField(
                related_name="_mailing_segment_municipio_of_origin_+",
                to="geodata.MexicanMunicipio",
                verbose_name="Municipio mexican d'origine",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="state_of_origin",
            field=models.ManyToManyField(
                related_name="_mailing_segment_state_of_origin_+",
                to="geodata.MexicanState",
                verbose_name="État mexicain d'origine",
                blank=True,
            ),
        ),
    ]
