# Generated by Django 3.2.20 on 2023-11-08 19:09

import agir.lib.model_fields
import agir.mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0055_auto_20231020_1808"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("CAM", "Newsletter Claudializate"),
                        ("ACT", "Newsletter Red Migrante"),
                        ("LIA", "Correspondant·es d'immeuble ou de rue"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=agir.mailing.models.default_newsletters,
                help_text="Inclure les personnes abonnées aux newsletters suivantes.",
                size=None,
            ),
        ),
    ]
